---
title: "Meetings"
---

<style>
body {
  text-align: justify}

h1 {
  text-align: center
}
</style>

We kicked off our interest group with an online Autumn series in 2023. In 2024, we had a special Winter session, a Spring series, as well as an Autumn series. You can find our upcoming and past meetings below, including our 2025 Spring series. To join our sessions, please send an email to 'discomatix [dot] group [at] gmail [dot] com'.

## Upcoming meetings

**All sessions take place at 16:00 CE(S)T**

September 16 - **XPrag 2025 satellite event**

We are preparing an in-person DiscoMatiX event, which will take place as a satellite event to XPrag 2025 in Cambridge (UK), a day before the main conference. See [XPrag 2025 satellite event](https://discomatix.github.io/satellite-event.html) for more information.

## Past meetings

<details>
<summary>**Spring series 2025**</summary>

<details>
<summary>June 10 - **[Hannah Rohde](https://www.lel.ed.ac.uk/~hrohde/)**, **University of Edinburgh**</summary>

**Why am I saying this? Sensible and informative contributions to discourse**

For a conversation to be coherent, we expect more than just a sequence of arbitrary sentences -- we expect the sentences to connect in predictable and sensible ways.  At the same time, if everything a speaker said were entirely predictable, there'd be no new information conveyed.  These two expectations -- one for plausibility, one for informativity -- are two key components that underlie cooperative communication.  This talk presents a series of case studies on what speakers choose to talk about and what forms they use, with subsequent tests of how such choices in turn influence comprehenders' expectations, notably when they're estimating what words are coming next and when they're trying to recover a speaker's intended meaning.

*For a recording of this talk, send us an email.*
</details>

<details>
<summary>May 13 - **[Diana Mazzarella](https://sites.google.com/site/mazzarelladiana/)**, **University of Neuchâtel**</summary>

**Understanding irony (mis)understanding**

Verbal irony typically involves making a statement that expresses a proposition the speaker believes to be false or irrelevant, not with the intention to deceive the addressee, but rather to prompt the addressee to recognise the speaker’s implicit dissociative attitude toward that proposition. As a result, understanding irony arguably involves grasping its epistemic, intentional, and attitudinal components.

How does research in experimental and developmental pragmatics measure irony understanding? In this presentation, I discuss some of the methodological challenges involved in designing experiments that investigate children’s developing understanding, or adults’ processing, of verbal irony. On the one hand, I illustrate the key role of various contextual features in modulating participants’ responses. On the other hand, I reflect on the delicate balance between capturing spontaneous interpretations and oversimplifying measures, risking the overinterpretation of participants’ behaviour.

*For a recording of this talk, send us an email.*
</details>
</details>

<details>
<summary>**Autumn series 2024**</summary>

<details>
<summary>December 10 - **[Irene Mognon](https://irenemognon.eu/)**, **University of Frankfurt** and **[Petra Hendriks](https://www.let.rug.nl/~hendriks/personal/index.html)**, **University of Groningen**</summary>

**Reconciling Scalar Implicature Theories with Processing Data**

Like other disciplines, linguistics relies on theory development as a vital component of its empirical research cycle. Ideally, experiments should test theories, and theories should inform experiments, with continuous cyclic interactions between the two. In this talk, we will focus on two prominent theories of scalar implicatures: the Grammatical Theory and the Relevance Theory framework. We will illustrate how each of these theories has received markedly different interpretations in the experimental literature, leading to contradictory predictions regarding the processing steps and the time course of scalar implicature generation. For example, whereas some experimental studies predicted - based on the Grammatical Theory - that the decision to generate scalar implicatures should be cognitively costly, other experimental studies based on the same theory predicted that cognitive effort or delays should not be observed in association with scalar implicature generation.

These contradictory predictions show the importance of spelling out and clarifying the often hidden assumptions of linguistic theories. Furthermore, they suggest that since linguistic theories often rely on assumptions from other fields of cognitive science, it is essential to carefully consider the alignment between linguistic theories and other relevant theories of cognition. This will allow researchers to optimally engage in the empirical cycle and shed more light on the characteristics and processing of scalar implicatures in particular, and pragmatics more in general.

*For a recording of this talk, send us an email.*
</details>

<details>
<summary>November 19 - **[Paula Rubio-Fernández](https://www.mpi.nl/people/rubio-fernandez-paula)**, **Max Planck Institute for Psycholinguistics**</summary>

**The Cognitive Trinity of Common Ground**

Human communication is built around interlocutors’ common ground (CG), or the information they assume to share. Despite having been the focus of intense interdisciplinary research for more than 60 years, we do not yet understand how CG works, or even what exactly it is. In this talk I will introduce a new research program that is essential to understanding CG: I propose to study CG as a product of cultural evolution. This approach requires identifying (i) those cognitive capacities that are required for the emergence of CG in human cognition, and (ii) how those capacities interact in (a) the development of CG through children’s social learning across cultures; (b) its formation through social interaction across the lifespan, and (c) its management in conversation across languages. I hypothesize that forming and using CG is a complex human ability that emerges from the interaction of three cognitive capacities — joint attention, shared memory, and the use of reference systems — under a rationality principle. This is what I informally call the *Cognitive Trinity of Common Ground*, which could also be described as a naïve model of rational memory.

*For a recording of this talk, send us an email.*
</details>

<details>
<summary>October 15 - **[Gareth Carrol](https://www.birmingham.ac.uk/staff/profiles/elal/carrol-gareth)**, **University of Birmingham**</summary>

**He’s a real weasel: designing a way to investigate markers of stance and metaphorical meaning with different reading measures**

In this talk I will discuss an ongoing work-in-progress project (with Vinicius Macuch) looking at the interpretation of words like “real”, which can convey literal or non-literal meaning (in this case, serving a more pragmatic role as an intensifier in examples like “a real piece of work” or “a real weasel”). We are interested in how readers interpret “real” as a part of incremental, online processing, and how this interacts with aspects such as conventionality (i.e. whether the thing being intensified has a clear, established metaphorical meaning). The focus of this talk is how we can design a study to investigate this, focusing on aspects like how specific word choices / combinations might change interpretations, how more / less conventionalised meanings might lead to different outcomes, and how other cues might need to be controlled and / or manipulated. I will also consider how and why different methods – online self-paced reading vs. lab-based eye-tracking while reading - might give complementary results, and what this means for the design of stimuli.

*For a recording of this talk, send us an email.*
</details>
</details>

<details>
<summary>**Spring series 2024**</summary>

<details>
<summary>June 11 - **[Tatjana Scheffler](https://tscheffler.github.io/)**, ***Ruhr-Universität Bochum***</summary>

**Experimental Approaches to the Semantics and Pragmatics of Emojis**

Emojis are frequently used in digital communication: some estimates state that about every second chat message contains an emoji. This, together with the fact that they have replaced a range of other non-standard features of online writing, indicates that emojis fill a linguistic gap and carry important semantic and pragmatic information.
Recently, linguists have started to address the specific semantic and pragmatic role of emojis not only theoretically and based on corpus data, but also experimentally. In the talk, I will present recent research we have carried out jointly with collaborators, investigating the meaning of different types of emojis using rating studies, but also self-paced reading and free text questions.

In particular, I will report recent results on deriving semantic norms for face emojis (from four language communities) from human participants, and testing the subtle meaning differences between emojis that look visually similar. In this experiment, we compared emoji pairs with a visual difference that either does or does not correspond to a difference in human facial expressions according to an adaptation of the Facial Action Coding System. Our results show that the small differences between emoji pairs are meaningful in all pairs whether or not they correspond to human facial differences. This supports a lexicalist approach to emoji semantics, which treats face emojis as conventionalized signals rather than mere pictures of faces.

*For a recording of this talk, send us an email.*
</details>

<details>
<summary>May 14 - **Panel discussion with [Ira Noveck](https://sites.google.com/site/iranoveck)**, ***Centre National de la Recherche Scientifique***, **[Napoleon Katsos](https://sites.google.com/site/napoleonkatsos/home)**, ***University of Cambridge***, **[Petra Schumacher](https://idsl1.phil-fak.uni-koeln.de/en/personen/professorenseiten/prof-dr-petra-b-schumacher)**, ***University of Cologne***</summary>

**The past, present, and future of experimental pragmatics**

For our special panel session we have invited three of the founding figures of the experimental pragmatics research program: Ira Noveck (Centre National de la Recherche Scientifique), Napoleon Katsos (University of Cambridge), and Petra Schumacher (University of Cologne). Their extensive experience in the field and varying backgrounds promise a lively discussion on some of the core questions in our field. The panelists will share their insights into questions related to the bridging of theory and experimental practice, methodology, as well as the current theoretical landscape and how it affects the future of experimental research on discourse and pragmatics, as well as questions from the audience.

*For a recording of this talk, send us an email.*
</details>

<details>
<summary>April 9 - **[Nicole Gotzner](https://sites.google.com/view/nicolegotzner)**, ***Osnabrück University***</summary>

**Bringing Grice to the lab: How to do interactive experiments on pragmatics and communication**

Since Grice’s monumental proposal, communication is construed as a cooperative enterprise involving a speaker and a hearer. Yet most experimental research in Cognitive Science is monadic and this is at odds with the fact that communication is a joint activity (Pickering and Garrod, 2021). Moreover, it presents us with an empirical gap: almost no fair empirical test of the Gricean model exists. I will discuss two strands of research that try to close this gap. (1) Work on implicature with interactive dialog experiments (e.g. Gotzner and Benz, 2018; Benz and Gotzner, 2021) and (2) ongoing research on referential communication about concepts with Kristina Kobrock and Charlotte Uhlemann. At the end of my talk, I will briefly discuss how multi-agent modeling tools can be used to tackle core questions about communication.

*For a recording of this talk, send us an email.*
</details>
</details>

<details>
<summary>**Winter session 2024**</summary>

On February 6 we had a special themed session on multimodality in discourse and pragmatics with 5-min flash talks by the speakers below. 

**[Anita Slonimska](https://www.mpi.nl/people/slonimska-anita)**, ***Max Planck Institute of Psycholinguistics***

**Rethinking communicative efficiency: Insights from sign languages**\
\

**[Jonas Nölle](https://scholar.google.co.uk/citations?user=iISC70gAAAAJ&hl=en)**, ***University of Glasgow***

**More than affect: Facial expressions serve as pragmatic signals in multimodal communication**\
\

**[Schuyler Laparle](https://sites.google.com/view/schuyler-laparle/)**, ***Tilburg University***

**The iconicity of abstract structure: Gesturing discourse relations**


*For a recording of this session, send us an email.*
</details>

<details>
<summary>**Autumn series 2023**</summary>

<details>
<summary>December 6 - **[Vera Demberg](https://www.uni-saarland.de/lehrstuhl/demberg/members/verademberg.html)**, ***Saarland University***</summary>

**Combining experimental work with computational modelling to better understand pragmatic processing**

In this talk, I will argue that complementing experimental research with computational modelling can be highly beneficial for developing a deeper understanding of pragmatic processing in humans. I will illustrate this claim with an example from current research at our lab, where we investigated how comprehenders adapt to speaker-specific use of uncertainty expressions (e.g., one speaker uses the word “probably” rather generously in situations where the probability of the event is not all that high, vs. another speaker who uses the word “probably” more cautiously). Specifically, we were interested in individual differences between study participants with respect to how strongly they adapt their expectations / interpretations to how they have experienced the two speakers use uncertainty expressions like “probably”. We examined how any differences in adaptation are related to individual differences between participants (working memory updating, reasoning ability, linguistic experience, theory of mind abilities). In the experiment we found a correlation between adaptation strength and abilities in terms of working memory updating as measured by the keep track task. I will discuss our efforts in constructing a computational model of this effect, and what additional questions this exercise brought up.

*For a recording of this talk, send us an email.*
</details>

<details>
<summary>November 15 - **[Ingmar Brilmayer](https://idsl1.phil-fak.uni-koeln.de/personen/lehrende-a-z/dr-ingmar-brilmayer)**, ***University of Cologne***</summary>

**Combined eyetracking and EEG in an interactive setting: the what, the why and the wherefore**

In this talk, I will talk about setup, data recording and data analysis in our interactive laboratory in Cologne. In the first part of the talk, I will talk about the requirements for interactive research in terms of hardware and software. In the second part of the talk, I will present two studies that we designed and conducted in our lab, the difficulties with building the experiment, as well as with data analysis that arise from the naturalistic design of the studies. In the last part, I will present results of these experiments, showing that, despite all the difficulties, it is worth the effort.

*For a recording of this talk, send us an email.*
</details>

<details>
<summary>October 18 - **[Chris Cummins](https://www.crcummins.com/)**, ***University of Edinburgh***</summary>

**Psychic linguistics?**

Readers of experimental linguistics papers can occasionally be struck by a curious sensation. Based on what’s in the methods section, you don’t know whether a particular manipulation will make a difference to the outcome variable (say, response time), or in which direction it will shift if so. But when you look at the full lists of stimuli, you suddenly develop a strong sense of what’s going to happen, and that premonition comes true upon reading the rest of the paper.

In this talk I use this idea briefly to discuss three points: whether we’re allowed to ‘accidentally’ introduce confounds in our materials; how the main-text examples in a paper relate to what’s in the appendix; and under what circumstances it’s really necessary to leave the armchair and actually run a study.
</details>
</details>
