---
title: "Mission statement"
---

<style>
body {
  text-align: justify}

h1 {
  text-align: center
}
</style>

**Under construction**

The field of discourse and pragmatics is characterized by many different frameworks (i.e. Neo- and Post-Gricean pragmatics, theories of discourse structure, information theoretic approaches, etc.). We believe that empirical data can help to further develop these theories, but applying well-known psycholinguistic techniques in this area is challenging for two reasons: first, the gap between abstract theoretical constructs and testable predictions is large; second, the contextual nature of discourse and pragmatics is difficult to implement with experimental paradigms that have been optimized for word- and sentence processing. Plausible communicative contexts are crucial for eliciting natural pragmatic behavior and generalizing our findings, but negatively influences the experimental control. Through this interest group, we hope to contribute to aligning different frameworks and enhancing experimental approaches.