---
title: "DiscoMatiX panel discussion XPrag 2025"
---

<style>
body {
  text-align: justify}

h1 {
  text-align: center
}
</style>

## Theme

**Discourse relations and coherence**

Discourse relations are an inherently situated phenomena, sitting at the corner of language use and grammar. On the one hand, they challenge theories of grammar since their properties extend beyond single sentences (or propositions), and thus the purview of certain theories of grammar. On the other hand, they demonstrate that principles exist which determine and constrain how the sentences (propositions) of discourse may or may not be connected. This duality makes them challenging to study, as well as the fact that discourses often involve language users interacting with the world and with each other dynamically. Discourse relations and coherence are thus of interest to formalists, taxonomists, computationalists, psycholinguists and philosophers.

Many theories of discourse structure and coherence have been put forward to try and capture these processes and how they are realized in various instances and contexts of language use. In this panel discussion, we bring together two experts working on discourse structure and coherence from different perspectives, with the goal of problematizing the phenomenon: What is a theory of discourse structure/relation? What are the necessary and sufficient criteria for it? Which empirical facts are of central importance, and which present challenges? Finally, how does the theory relate to theories of language and its use? 

We invite our speakers to take a meta-stance by tackling how they have approached the study of discourse coherence in their research, what they think the strengths and weaknesses of their particular frameworks/approach are, and how they think work in these frameworks relates to work in other frameworks. 

## Invited panelists

[Daniel Altshuler](https://danielaltshuler.com/) (University of Oxford, UK)

Daniel is an associate professor of semantics in the Faculty of Linguistics, Philology and Phonetics at the University of Oxford and the dean and tutorial fellow of Jesus College, and lecturer of Brasenose College. He received his PhD in 2010 from Rutgers University. His work often confronts issues at the intersection of linguistics, philosophy and cognitive science, and has worked on a range of topics in the semantics and pragmatics from the semantics of tense and aspect to anaphora and coherence.

[Jet Hoek](https://jethoek.github.io/) (Radboud University, The Netherlands)

Jet is an assistant professor at Radbound University Nijmegen's Department of Language and Communication. She received her PhD in 2018 from Utrecht University, and has been a postdoc at the University of Edinburgh as well as at the University of Cologne. Her work surrounds issues in discourse, specifically the study of coreference and coherence relations from a cognitive perspective.

## Logistics

**When & where**

September 16, 14:30 - 17:30

University of Cambridge, Cambridge, UK

**Format & schedule**

Introduction (14:30 - 14:40)

Speaker 1 (14:40 - 15:30)

Break 1 (15:30 - 15:40)

Speaker 2 (15:40 - 16:30)

Break 2 (16:30 - 16:40)

Discussion (16:40 - 17:30)

**Registration**

If you would like to register for the event, please use the link below and follow the instructions on the Evenbrite page.

https://www.eventbrite.com/e/discomatix-xprag-2025-satellite-event-tickets-1383405967489?aff=oddtdtcreator&utm-source=cp&utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing